a = {'output': '''Here\'s the adapted prompt for Boat and Boat Headphones:\n\n<revised_prompt>\nYou are tasked with creating a concise version of a paraphrased account from a user research interview for the headphone brand Boat. This concise version will be used to compare with other interviews from the same study to identify differences. Your goal is to capture important points related to the study objectives while maintaining nuance.\n\nHere is the paraphrased account:\n\n<paraphrased_account>\n"(paraphrased_account)"\n</paraphrased_account>\n\nThe objectives of the study are:\n1. Profiling the customers of Boat\n2. Brand perceptions for Boat among its users and perceptions of other brands\n\nTo create the concise version:\n\n1. Carefully read through the paraphrased account.\n2. Identify key information related to the study objectives, such as:\n   - Customer demographics and characteristics\n   - Purchasing behavior and preferences\n   - Opinions and experiences with Boat products\n   - Perceptions of Boat as a brand\n   - Comparisons with or mentions of other headphone brands\n\n3. Summarize this information in a concise manner, maintaining important details and nuances.\n4. Ensure that the concise version captures the essence of the original account while being significantly shorter.\n5. Use clear and precise language to convey 
the information.\n\nPresent your concise version within <concise_account> tags. Aim for a length of about 30-50% of the original paraphrased account, depending on the density of relevant information.\n</revised_prompt>''', 'prompt_tokens': 1547, 'completion_tokens': 364}


b = {'output': "Here's the adapted prompt for Boat Headphones:\n\n<revised_prompt>\nYou are tasked with identifying relevant questions from a user research interview about the headphone brand Boat. The questions are organized by sections. Your goal is to select questions that might help answer a specific research objective.\n\nFirst, review the sections and questions from the user research interview:\n\n<sections_with_questions>\n{{sections_with_questions}}\n</sections_with_questions>\n\nNow, consider the following research objective:\n\n<research_objective>\n{{research_objective}}\n</research_objective>\n\nAnalyze the sections and questions carefully. Your task is to identify questions that are most likely to provide information relevant to answering the given research_objective.\n\nTo complete this task:\n\n1. Read through all the sections and questions.\n2. Consider how each question might relate to the research objective and the questions therein.\n3. Select questions that you believe would provide useful information for answering the research objective and the questions therein.\n\n</revised_prompt>", 'prompt_tokens': 1010, 'completion_tokens': 228}

c = {'output': "Here is the adapted prompt for Boat Headphones:\n\n<revised_prompt>\nYou are tasked with analyzing paraphrased accounts from user research interviews conducted for audio brand Boat. Your goal is to identify the differences between these accounts to help formulate objectives for the study that incorporate analysis of such differences.\n\nHere are the paraphrased accounts from the user research interviews:\n\n<paraphrased_accounts>\n{{paraphrased_accounts}}\n</paraphrased_accounts>\n\nPlease carefully read and analyze these accounts. Pay close attention to differences in the following areas:\n\n1. Demographics: Age, gender, lifestyle, location, etc.\n2. Purchasing behavior: Frequency of purchases, preferred shopping channels, etc.\n3. Product preferences: Types of headphones, features, audio quality, etc.\n4. Brand perceptions: Awareness of Boat, opinions about the brand, comparisons with competitors, etc.\n5. Decision-making factors: Price, sound quality, battery life, design, recommendations, etc.\n\nAfter your analysis, please provide the following:\n\n1. A summary of the key differences you've identified between the accounts. Include specific examples from the paraphrased accounts to support your observations.\n\n2. Based on these differences, suggest 3-5 potential objectives for the study. These objectives should aim to explore and understand the variations in customer experiences, preferences, and perceptions.\n\nPresent your findings in the following format:\n\n<key_differences>\n[List the key differences you've identified, organized by the areas mentioned above]\n</key_differences>\n\n<suggested_objectives>\n[List 3-5 potential objectives for the study based purely on the identified differences]\n</suggested_objectives>\n\nEnsure that your analysis is thorough and that the suggested objectives are specific, measurable, and relevant to understanding the variations in customer experiences with Boat Headphones.\n</revised_prompt>", 'prompt_tokens': 1394, 'completion_tokens': 421}


print(c["output"])